### ISSUE TITLE
Option to import/export CMIS settings.

### ISSUE THREAD

**Issue by choobin** [choobin/cmis#10]
AMO user Kevin made the following feature request as a comment on the CMIS download page.

>  A way for us to export/import our paths for backup reasons (just in case).

This is a great idea. It gets quite annoying having to recreate complex CMIS settings now and then.

**Comment by KevinSanders** [comment]
I have way too many. haha. I use a lot of image references for 2D and 3D work, etc.

**Comment by choobin** [comment]
Initial implementation in [b1ad16f2d1](https://github.com/choobin/cmis/commit/b1ad16f2d109c10ca19a6368afbb1c3ea87659f1). 

It works fine. However there is one issue I am still pondering over. Currently it only imports/exports menu configurations. That is, it does not save any user preferences, for example, where the menu is placed or the file overwrite behavior. I am happy with this for the time being. The import/export options are located on the menu dialog (not the main options page). However, I might revisit this issue in the future.
