### ISSUE TITLE
Options for status bar notification of saved image.

### ISSUE THREAD

**Issue by choobin** [choobin/cmis#11]
AMO user Kevin made the following feature request as a comment on the CMIS download page.

> Add a status bar message (just to show it was saved).

This might fit in the advanced settings tab. 

Personally I use the 'Download Statusbar' extension. This shows a temporary notification in the status bar. However, I do see the need for users that do not have this installed. Some sort of notification is necessary.

**Comment by KevinSanders** [comment]
Hi Choobin, 
Agreed...any sort of notification would be fine.

**Comment by nhantrn** [comment]
@KevinSanders You could install Statusbar-4-Ever addon and it will shows you download status when saving images. https://addons.mozilla.org/en-US/firefox/addon/status-4-evar/

It restores the statusbar that used to be in legacy FF3.6 before Mozilla had the genius idea to replace it with the useless addon bar.

**Comment by KevinSanders** [comment]
Thanks for the link nhantrn! The "Statusbar-4-Ever" add-on is nice. I've used "Download Statusbar" (as Choobin mentioned above) in the past. But I'd rather something as part of this add-on though, without having to install extra add-ons (I already have loads...lol).

**Comment by choobin** [comment]
Just some notes for implementation.

It looks like the status bar was [deprecated](https://developer.mozilla.org/en-US/docs/XUL/statusbar) a long time ago (FF4.0). 

We can achieve similar functionality by calling, [nsIXULBrowserWindow.setOverLink](https://developer.mozilla.org/en-US/docs/XPCOM_Interface_Reference/nsIXULBrowserWindow#setOverLink(\)).

**Comment by choobin** [comment]
Implemented in [85a5eec19b](https://github.com/choobin/cmis/commit/85a5eec19b451dc750a827cb4e39ff740aa6c643). 

It is using setOverLink. I have encountered a slight issue here. If the mouse is on top of a link when the context menu closes Firefox will call setOverLink for the link and replace our notification. If this becomes an problem please re-open this issue and I will look into it further.
