### ISSUE TITLE
Suffix for image name

### ISSUE THREAD

**Issue by KevinSanders** [choobin/cmis#14]
Could you please add a suffix field? Sometimes I like to append words related to an image so I can easily find them later in a search (as they can cross various folders, ie: 1920's (clothes, architecture, transport, etc).

**Comment by choobin** [comment]
Just for clarification. You mean before the actual file suffix right? 

For example, %PREFIX_%NAME_%SUFFIX.jpg where .jpg is the file suffix.

I was thinking of scrapping the prefix field altogether and having a entry to configure the complete filename. That is, introduce new variables such as, %NAME, %FILESUFFIX, %URI, %{other stuff that might be handy}.

**Comment by KevinSanders** [comment]
Oh yes, before the actual file suffix (*.jpg, etc),

Complete file naming variables would be a great. Thanks!

**Comment by choobin** [comment]
This has been addressed in [d40334356f](https://github.com/choobin/cmis/commit/d40334356fc3659dfe1de04c2c48cecada7d24f6).

The 'prefix string' property has been removed in place of 'format string' which gives control over the complete format of file name. This is a much better solution than having a prefix and suffix field. The new format variables are displayed in the edit dialog.
