### ISSUE TITLE
Insert new menu items under this.selection.currentIndex

### ISSUE THREAD

**Issue by choobin** [choobin/cmis#16]
Kevin Sanders made an insightful comment in issue/5 regarding placement of new items. 

> This is somewhat related, when creating a new folder path and you already have one selected on the left, it would be nice if it creates the new folder as a sub-folder of the currently selected one.

Implementation notes:

This occurs in src/content/items.js:treeview.insert.

The selected item is this.selected.currentIndex.

**Comment by choobin** [comment]
Implemented in [3d78ccce6c](https://github.com/choobin/cmis/commit/3d78ccce6c831d3e3da4fa291197a539dcc79cd7).

**Comment by KevinSanders** [comment]
I've downloaded/installed the latest source. This is working GREAT. Thanks!
