### ISSUE TITLE
Undo/Redo options when editing menu layout.

### ISSUE THREAD

**Issue by choobin** [choobin/cmis#17]
I have been burnt too many times accidentally deleting a large sub-menu and complex items.

Provide options to undo/redo menu editing actions.

**Comment by KevinSanders** [comment]
This is interesting, but I think the export/import settings may be better? Maybe they can auto save when the user is finished tweaking them? (once they press "Done") ...and then just import the last good one?

But yes Undo/Redo is a nice idea!

**Comment by choobin** [comment]
Undo/Redo with Ctrl-Z/Ctrl-Y shortcuts -- [01c60055b2](https://github.com/choobin/cmis/commit/01c60055b209729064c0156d65fdd7f12a590eeb) -- very neat.

**Comment by KevinSanders** [comment]
Excellent. Works great! :)
