### ISSUE TITLE
Larger (vertical) default Settings window size

### ISSUE THREAD

**Issue by KevinSanders** [choobin/cmis#18]
At the moment on my monitor, the settings window opens at approximately 30% of the vertical screen size. Can you make this taller by default? I have to constantly resize it every time I open it.

**Comment by choobin** [comment]
Interesting. It looks like there was no minimum height value set. I have tentatively set it to 500px [fa103ad516](https://github.com/choobin/cmis/commit/fa103ad516a8c0c5a7d16648703ff08849a4aba5).

**Comment by KevinSanders** [comment]
The latest version is perfect thanks! (No need for me to maximize the window any more)
