### ISSUE TITLE
"Generate menu from a directory tree" tweaks

### ISSUE THREAD

**Issue by KevinSanders** [choobin/cmis#19]
This is working great! But can you add it as a button on the right-hand side instead (for new users, etc)

One thing, if I manually add/remove a folder outside of firefox, it would be nice if we could update the existing generated directory tree. Currently if I open the "Edit" window for the ROOT item of the generated tree, it just displays the root address. Can you add a button for "Rebuild directory tree" ? (if possible). Thanks

**Comment by choobin** [comment]
Indeed 'Generate Menu' fits nicely in the button list [2530140a7d](https://github.com/choobin/cmis/commit/2530140a7d217af0d1c029e7ac50e42929d40d2b).

> One thing, if I manually add/remove a folder outside of firefox, it would be nice if we could update the existing generated directory tree.

This can also apply to normal items. That is, if an items path is deleted what should happen? From memory I think CMIS will create the path again before it calls save. I do not know if this is desired though. Nobody has mentioned it yet (:

> Currently if I open the "Edit" window for the ROOT item of the generated tree, it just displays the root address. Can you add a button for "Rebuild directory tree" ? (if possible). Thanks

I have opened an [issue/23](https://github.com/choobin/cmis/issues/23) for this. However, I will not know if I will get to it for a while. I need to throughly test all the new features and do a proper release on AMO first.
