### ISSUE TITLE
Import/Export settings

### ISSUE THREAD

**Issue by KevinSanders** [choobin/cmis#20]
It exports the full contents of user paths. But what I find after testing twice, it puts what was Root folders in the menu as sub-folders of some root folders.

Example: I had a folder structure similar to this:

2D (submenu item)
--- Paintings
--- Sketches
--- Graphic

3D (submenu item)
--- ZBrush
--- Maya
--- Characters
--- Vehicles

But when I cleared everything from the settings and imported my backup, I got this

2D
--- Paintings
--- Sketches
--- Graphic
--- 3D
------- ZBrush
------- Maya
------- Characters
------- Vehicles

Where the 3D root folder (submenu item) was nested inside the 2D folder.

**Comment by KevinSanders** [comment]
Also, when I removed all of my custom paths (before importing them back in), there was no trace of CMIS in the context menu. I had to go to the add-on page and proceed from there. It would be great if you had a default position at top of the context menu (or as specified in the settings). Personally as the top-most item is best as it gives quick and easy access to CMIS. "Open Settings" or similar would be an ideal default.

Maybe with a little icon on the left like this?
http://img46.imageshack.us/img46/158/addfolder.png

**Comment by KevinSanders** [comment]
Another thing I just noticed when trying to re-arrange the menu after importing. I had to click UP/DOWN to move the root folder back into a root position, clicking multiple times. Could you add a button on the right side "Make Root", <-- or something? So it jumps to the main root position? Or something similar to this at least.

OR much better if possible, the ability for the user to Drag the folder into the position they want?

**Comment by choobin** [comment]
Thanks for spotting that. Looks like one more test case to add to the list. I fixed the issue in [186e731a43](https://github.com/choobin/cmis/commit/186e731a437df64fc219c9b08282252ba4262196).

Regarding you two other comments. All good ideas. Seriously, thanks for all of the suggestions. I have created a new issues for them so they do not get lost.

[issue/21](https://github.com/choobin/cmis/issues/21) 
[issue/22](https://github.com/choobin/cmis/issues/22)

**Comment by KevinSanders** [comment]
You're totally welcome! I truly appreciate your time invested in tweaking your great add-on.

Import/Export is now working as expected.
