### ISSUE TITLE
The experimental feature "Save links not just images" doesn't work.

### ISSUE THREAD

**Issue by choobin** [choobin/cmis#26]
@nhantrn mentioned in another issue

> ... I notice that the experimental feature "Save links not just images" doesn't work. When I right click on a thumbnail to save the linked image, it saves the thumbnail instead of the linked image. You can test that out on this page http://www.autowp.ru/picture/eu3m7a

**Comment by choobin** [comment]
Consider the following HTML snippet.

`<a href="..."><img src="..." /></a>`

If the "Save links not just images" option is set what should get priority, the image or the link?

In the URL @nhantrn mentioned, the car is both a thumbnail image and a link to a larger image. Currently CMIS prioritizes the image and the thumbnail will be saved.

The image take priority here because this is the purpose of the extension, that is, to save images.

It could save the image and the link? Although, that could get annoying.

**Comment by nhantrn** [comment]
Actually, you're right, if it's just a link to an image, then the linked image get saved. However, the thumbnail link is the problem. You should work this out. Perhaps you should make a distinction between "Save Image As..." and "Save Link As..."

**Comment by choobin** [comment]
> Perhaps you should make a distinction between "Save Image As..." and "Save Link As..."

Exactly. The troubling aspect of this is where should the distinction be made?

I completely understand the reason for the developer of "Save Image in Folder" to develop a separate extension for "Save Link in folder". It's tough, really tough.

**Comment by nhantrn** [comment]
Can you explain what js method you are using to save image? I notice saving image doesn't get recorded in Firefox's download manager.

Maybe you could piggyback ride Firefox's save functions. That way you won't have to bother with extra codes to make distinctions at all.

**Comment by choobin** [comment]
@nhantrn. I am using the internal function [nsIWebBrowserPersist.saveURI](https://developer.mozilla.org/en-US/docs/XPCOM_Interface_Reference/nsIWebBrowserPersist?redirectlocale=en-US&redirectslug=nsIWebBrowserPersist#saveURI%28%29) for downloading. Note that by default I have configured it to pull the image from the cache if it is there.

It should show up in the download manager. It is one of my test cases. Do you have the download dialog open (Crtl-J)? 

I do not think it opens the dialog like Firefox optionally does. However, I am 100% sure that it send the save action to the download manager. [Here](https://github.com/choobin/cmis/blob/master/src/bootstrap.js#L494-L514) is the code that achieves this .

**Comment by choobin** [comment]
@nhantrn With further investigation into the issue I have discovered that arguments to saveURI were incorrect. This was preventing correct communication with the download manager on some combinations of OS/FF.  This was fixed in [9393599eaa](https://github.com/choobin/cmis/commit/9393599eaa9ac4809b7372d9f5e862705f81a72b) and will make it into the next release. Cheers.

**Comment by choobin** [comment]
Forgot to close this issue with my last comment.
