### ISSUE TITLE
"Save as..." : allow pre-formatted name

### ISSUE THREAD

**Issue by nerbrume** [choobin/cmis#28]
Following Issue #8, would it be possible to specify a default name for the saved image, even when we open the "save as" dialog ?

Ergonomy-wise, if this is done, I think that rather than adding a new kind of "item" in the menu, adding a checkbox labelled "open save dialog" in the standard item creating dialog would make more sense.
If I'm not clear, enough, tell me, I'll make a mock-up.

**Comment by choobin** [comment]
A fantastic idea. Cheers.

**Comment by choobin** [comment]
Oops. Reopen. No more github on the phone for me.

**Comment by choobin** [comment]
Sigh.

**Comment by choobin** [comment]
Just a follow up. Apologies. I have been away and was having lots of trouble with my _ridiculous_ phone. 

This is a great idea. Before the next release I will remove the 'Save Image As' button and integrate it as an option to the 'Item' type. Cheers.

**Comment by choobin** [comment]
Added in [bda92d9774](https://github.com/choobin/cmis/commit/bda92d97745824bb1059715c62e4ad8243bac058).

The Item and Save As item have been merged together with the inclusion of an option to open the save as dialog before save.

**Comment by nerbrume** [comment]
Great, thanks !
(funny : I had a look at it myself this week-end, and even implemented a working version (fairly easy, since you did all the hard work), and was about to report it here, but you beat me to it !)

**Comment by choobin** [comment]
Ahhh drats. Hey, thanks anyway. Contributions are very welcome.
