### ISSUE TITLE
Provice features akin to "Image Toolbar" extension

### ISSUE THREAD

**Issue by choobin** [choobin/cmis#33]
AMO user Lycian SAGE provided the following suggestion in a comment on the CMIS page.

> 1. I strongly suggest a toolbar which appears when you hoover the image (this toolbar was implemented in -now obsolete- "Image Toolbar" add-on: https://addons.mozilla.org/en-us/firefox/addon/image-toolbar/ ).
>    1.1. Toolbar will appear for a few seconds when hoovering. and then disappear even though you keep hoovering.
> 
> 1.2. Toolbar must be a small thing not a giant context-menu-like thing.
> 
> 1.3. User can turn the toolbar feature on and off.
> 
> 1.4. Toolbar should convey one or more buttons.
> 
> 1.5.1. If you have time; you can let user decide how many buttons there will be.
> 
> 1.5.2. Default button is "Save".
> 
> 1.5.2. There may be other buttons like "Save to <Item>" or "Show Image" and "Open Saved Folder".
> 
> 1.5.3. Four (max 5) buttons are enough I think.
> 
> 1.6. Save button, which is the default button, will do the job of Ctrl+RMB
> 
> 1.7. If you still have time, you can let user to move the place of the buttons on the toolbar (left or right to each other) just like moving the "Item"s up and down on the context menu. (this nuance will make your add-on more chic and more cool)

**Comment by KevinSanders** [comment]
IMHO I think it's overkill for CMIS.

**Comment by choobin** [comment]
I agree. Definitely out of scope for this extension. 

I have fond memories of image-toolbar from way back. It is a pity the developer has neglected it. If I get some spare time I might see about taking it on and updating it.
