### ISSUE TITLE
"Save image as..." doesn't work

### ISSUE THREAD

**Issue by simonbcn** [choobin/cmis#44]
`Firefox 21`
`Context Menu Image Saver 20130207`

I have created a "<i>Menu item setting</i>" with "<i>Open the 'Save Image As...' dialog before saving</i>" but it doesn't work.
I try to save this image http://www.mubis.es/titulos/el-lado-bueno-de-las-cosas-blu-ray/caratula with the name "<i>El lado bueno de las cosas (Silver Linings Playbook) (2012)</i>" but it doesn't save nothing.

**Comment by choobin** [comment]
G'day @simonbcn. Thanks for bringing this to my attention. Indeed, there seems to be an issue with saving after a 'Save Image As' dialog. Looking into it now.
