### ISSUE TITLE
Images do not save

### ISSUE THREAD

**Issue by hachimitsu** [choobin/cmis#52]
I am currently on Aurora 26.0a2 and images no longer save.

**Comment by choobin** [comment]
G'day,

Thanks for contacting me. FF26 deprecated the nsIDownloadManager interface and now uses Downloads.jsm to control the download manager. I updated CMIS in 5674790 to reflect this. Unfortunately, Downloads.jsm is still in development, i.e., it is still changing regularly. 

See here: https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Downloads.jsm 

and: http://hg.mozilla.org/mozilla-central/filelog/e85b0372cece/toolkit/components/jsdownloads/src/Downloads.jsm. 

I want to wait some time for it to stabilize before I update the current AMO version.

You can download the latest release from: https://github.com/choobin/cmis/releases/tag/20130916

This will work on FF26+. 

Take a look at the following page for instructions to install it: [https://github.com/choobin/cmis/wiki/How-to-test-the-latest-update-from-github.](https://github.com/choobin/cmis/wiki/How-to-test-the-latest-update-from-github.)

If you need a hand send me an email, happy to help out.

Cheerio,

choobin
