### ISSUE TITLE
%CLIPBOARD changes ":" character by "_"

### ISSUE THREAD

**Issue by simonbcn** [choobin/cmis#53]
I have set the file format as `%CLIPBOARD.%EXT` but if the clipboard content has character `:`, it's substituted by `_`. Why? In Linux this character is allowed in filenames.

**Comment by choobin** [comment]
Thanks for the feedback. Indeed, the only invalid characters on Linux are '\0' and '/'. Give me a second and I will update the filename validation function.

There will be a slight delay releasing this update to AMO. See issue #52 for details. If you want to check it out earlier please refer to the following page. [https://github.com/choobin/cmis/wiki/How-to-test-the-latest-update-from-github.](https://github.com/choobin/cmis/wiki/How-to-test-the-latest-update-from-github.)

**Comment by choobin** [comment]
Fixed in 0598c27.

**Comment by simonbcn** [comment]
Thanks for the fix. It works well.
