### ISSUE TITLE
%EXT doesn't work well

### ISSUE THREAD

**Issue by simonbcn** [choobin/cmis#54]
I have a entry with File format: `%CLIPBOARD.%EXT`.
But if the image name has more than 1 dot, it takes all characters after than the first dot like extension.
Example:
image name: `71I0vPD6YJL._SL1400_.jpg`

saved name: `Lago Eden (Eden Lake) (2008)._SL1400_.jpg`

**Comment by choobin** [comment]
Thanks for the bug report. I have determined the source of the issue. It is due to a particularly nasty regular expression in `Cmis.util.format`.

**Comment by choobin** [comment]
All fixed. Cheers mate. I will send the revision to AMO later this afternoon. It should be a week or so before it gets approved. If you would like to try it out earlier you can download the latest release [here](https://github.com/choobin/cmis/releases). Information about installing it from github can be found [here](https://github.com/choobin/cmis/wiki/How-to-test-the-latest-update-from-github.).
