### ISSUE TITLE
Append webpage caption.

### ISSUE THREAD

**Issue by choobin** [choobin/cmis#6]
AMO user pein0saga made the following feature request as a comment on the CMIS download page.

> APPEND WEBPAGE CAPTION
> (MANY IMG DEFAULT NAME IS MEANIGLESS)

My interpretation of the comment is to add an option to save using the IMG ALT text in place of the filename.
- gContextMenu.target.alt to get the alt text
- What if there is no alt text? Use the filename.
- Where to place the option? Make it specific to a menu item or as a global option in the settings page? Specific.

**Comment by gsxgmpkt9020** [comment]
This would be nice! Thank you!~

**Comment by nhantrn** [comment]
Is it possible in Javascript add metatags into saved images?

I would be really cool if there is an option to add the original URL of the image into the image's metatag.

**Comment by choobin** [comment]
> This would be nice! Thank you!~

I have made a start at modifying the prefix string to append alt text and timestamps to the filename. See [e344f21d85](https://github.com/choobin/cmis/commit/e344f21d85d8c8eabd544fb0f59ae9a38115cfa8). I need to do a lot more testing before I send it to AMO. If you would like to test it out yourself I can provide an XPI and/or document how to package and install the latest snapshot from github. See [How to test the latest update from github](https://github.com/choobin/cmis/wiki/How-to-test-the-latest-update-from-github.).

**Comment by choobin** [comment]
> Is it possible in Javascript add metatags into saved images?
> I would be really cool if there is an option to add the original URL of the image into the image's metatag.

That is a fantastic idea! Although, I need some time to think about the best way to do this. I have created an new [issue](https://github.com/choobin/cmis/issues/7) so it does not get lost. Thanks for the feedback.

**Comment by choobin** [comment]
Added to CMIS in [e344f21d85](https://github.com/choobin/cmis/commit/e344f21d85d8c8eabd544fb0f59ae9a38115cfa8).
