### ISSUE TITLE
'Save Image As' default download directory

### ISSUE THREAD

**Issue by choobin** [choobin/cmis#8]
AMO user Kevin made the following feature request as a comment on the CMIS download page.

>  for a selected folder, add option to "open" the folder for the user to navigate to saving into a sub-folder. For example, I have a folder path called "Animals", and sub-folders (cats, dogs, bats, horses, etc). I don't want to make a folder path for each sub-folder as I have 20+ in some for art reference.

An excellent suggestion. I can modify the 'Save As' button to set a default directory which can be configured by the user.

**Comment by KevinSanders** [comment]
That would be great per-parent folder. For example the user could have the parent folder (Animals or Fashion, Architecture, People, etc).

Thanks for the quick reply Choobin! :)

**Comment by choobin** [comment]
Save As items can now optionally select a default directory to start browsing from.
